CREATE TABLE ___Table__Defination___ (
    ID LONG, 
    Table Name TEXT, 
    PurposeOfUse TEXT,
);


CREATE TABLE Agent (
    AgentID TEXT, 
    AgentName TEXT, 
    AgentAddressLine1 TEXT, 
    AgentAddressLine2 TEXT, 
    AgentAddressLine3 TEXT, 
    AgentAddressLine4 TEXT, 
    AgentPostCode TEXT, 
    AgentOfficeEmail TEXT, 
    AgentPersonalEmail TEXT, 
    AgentHomeTel TEXT, 
    AgentMobile TEXT, 
    AgentOffice TEXT, 
    AgentOfficeAddressLine1 TEXT, 
    AgentOfficeAddressLine2 TEXT, 
    AgentOfficeAddressLine3 TEXT, 
    AgentOfficeAddressLine4 TEXT, 
    AgentOfficePostCode TEXT, 
    AgentOfficeTel TEXT, 
    AgentOfficePos TEXT, 
    AgentMemo MEMO, 
    AgentSageSuppAC TEXT, 
    Note TEXT, 
    BANK_ID TEXT, 
    CommissionType UNKNOWN, 
    CommissionAmt INTEGER, 
    VATReg TEXT, 
    AcBalance UNKNOWN, 
    PaymentMethod TEXT, 
    BacsRef TEXT, 
    HomeOfficeAdd BIT, 
    InactiveAgent BIT, 
    InactiveDate DATETIME, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    spare9 TEXT, 
    spare10 TEXT, 
    spare11 TEXT, 
    spare12 TEXT,
);


CREATE TABLE AttachedFile (
    FileID LONG, 
    FilePath TEXT, 
    FileName TEXT, 
    OwnerID TEXT, 
    NewFileName TEXT, 
    Entity TEXT, 
    NewFilePath TEXT, 
    FileType TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    isLinked BIT, 
    Description TEXT, 
    DateAdded DATETIME,
);


CREATE TABLE BACSPaymentRun (
    RunNo LONG, 
    RunDate DATETIME, 
    LineNo LONG, 
    EB LONG, 
    Description TEXT,
);


CREATE TABLE BankFund (
    ClientID TEXT, 
    BankCode TEXT, 
    FundID LONG,
);


CREATE TABLE Batches (
    Batch INTEGER, 
    First INTEGER, 
    Last INTEGER,
);


CREATE TABLE ChargeTypes (
    ID UNKNOWN, 
    FeeType TEXT, 
    FeeIC TEXT, 
    FeeSagePrefix TEXT, 
    FeeNCAmt TEXT, 
    FeeNNAmt TEXT, 
    FeeNCVat TEXT, 
    FeeNNVat TEXT, 
    FeeNCTotal TEXT, 
    FeeNNTotal TEXT, 
    TransactionType UNKNOWN, 
    CategoryCode UNKNOWN, 
    PaymentDates UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    RecoverableExp TEXT, 
    propertyID TEXT, 
    ClientID TEXT, 
    GroupID LONG, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE ChargingMethod (
    ChargingMethodID UNKNOWN, 
    ChargingMethod TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT,
);


CREATE TABLE Client (
    ClientID TEXT, 
    ClientName TEXT, 
    ClientAddressLine1 TEXT, 
    ClientAddressLine2 TEXT, 
    ClientAddressLine3 TEXT, 
    ClientAddressLine4 TEXT, 
    ClientPostCode TEXT, 
    ClientOfficeEmail TEXT, 
    ClientPersonalEmail TEXT, 
    ClientHomeTel TEXT, 
    ClientMobile TEXT, 
    ClientOffice TEXT, 
    ClientOfficeAddressLine1 TEXT, 
    ClientOfficeAddressLine2 TEXT, 
    ClientOfficeAddressLine3 TEXT, 
    ClientOfficeAddressLine4 TEXT, 
    ClientOfficePostCode TEXT, 
    ClientOfficeTel TEXT, 
    ClientOfficePos TEXT, 
    ClientMemo MEMO, 
    LandLordSageCustAC TEXT, 
    LandLordSageSuppAC TEXT, 
    Note TEXT, 
    BANK_ID TEXT, 
    Bank_AC_Name_ TEXT, 
    BANK_AC_NUM_ TEXT, 
    BANK_SC_ TEXT, 
    CommissionType UNKNOWN, 
    CommissionAmt INTEGER, 
    BGRPayable UNKNOWN, 
    VATReg TEXT, 
    AcBalance UNKNOWN, 
    Residency TEXT, 
    YearEndDate DATETIME, 
    PaymentMethod TEXT, 
    BacsRef TEXT, 
    HomeOfficeAdd BIT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    spare9 TEXT, 
    spare10 TEXT, 
    spare11 TEXT, 
    spare12 TEXT, 
    CompReg TEXT, 
    RegAdd1 TEXT, 
    RegAdd2 TEXT, 
    RegAdd3 TEXT, 
    RegAdd4 TEXT, 
    RegPostCode TEXT, 
    CT TEXT, 
    GroupCode TEXT, 
    Comments1 TEXT, 
    Comments2 TEXT, 
    RentSummaryTemplate TEXT, 
    PaymentType TEXT, 
    PaymentTerms LONG, 
    RemittanceTemplate TEXT, 
    ClientAddressLine5 TEXT, 
    ClientOfficeAddressLine5 TEXT, 
    RegAdd5 TEXT, 
    ConsolidatedStatement LONG, 
    StClientHomeTel TEXT, 
    StClientOfficeTel TEXT, 
    StClientMobile TEXT, 
    StClientPersonalEmail TEXT, 
    StClientOfficeEmail TEXT, 
    StToClientAddress LONG, 
    StToStatementAddress LONG, 
    AccountName TEXT, 
    SortCode TEXT, 
    AccountNumber TEXT, 
    UsePayableTemplate LONG, 
    BankPaymentRef TEXT, 
    LesseeTemplate TEXT, 
    ShowBankAccountFunds BIT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    LesseeAccTemplate TEXT, 
    CSPreviewTemplate TEXT, 
    CSTemplate TEXT, 
    CreatedBy TEXT, 
    CreatedDate DATETIME, 
    SelClient TEXT,
);


CREATE TABLE ClientGlobalData (
    Record_ID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    LettingFee BIT, 
    LettingAM TEXT, 
    LettingFreq TEXT, 
    LettingNtDueDt DATETIME, 
    LettingStDt DATETIME, 
    LettingChrgType UNKNOWN, 
    MngFee BIT, 
    MngAM TEXT, 
    MngFreq TEXT, 
    MngNtDueDt DATETIME, 
    MngStDt DATETIME, 
    MngChrgType UNKNOWN, 
    RentPayble BIT, 
    RentAM TEXT, 
    RentFreq TEXT, 
    RentNtDueDt DATETIME, 
    RentStDt DATETIME, 
    RentChrgType UNKNOWN, 
    QuarterlyDueDate1 TEXT, 
    QuarterlyDueDate2 TEXT, 
    QuarterlyDueDate3 TEXT, 
    QuarterlyDueDate4 TEXT, 
    HalfYearlyDueDate1 TEXT, 
    HalfYearlyDueDate2 TEXT, 
    MonthlyDueDate1 TEXT, 
    MonthlyDueDate2 TEXT, 
    MonthlyDueDate3 TEXT, 
    MonthlyDueDate4 TEXT, 
    MonthlyDueDate5 TEXT, 
    MonthlyDueDate6 TEXT, 
    MonthlyDueDate7 TEXT, 
    MonthlyDueDate8 TEXT, 
    MonthlyDueDate9 TEXT, 
    MonthlyDueDate10 TEXT, 
    MonthlyDueDate11 TEXT, 
    MonthlyDueDate12 TEXT, 
    YearlyDueDate TEXT, 
    FeeIsuDays INTEGER, 
    PayIsuDays LONG, 
    dueDate DATETIME,
);


CREATE TABLE ClientProAgr (
    CPA_ID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    RECHARGES UNKNOWN, 
    RRPA UNKNOWN, 
    REVIEW_DATE TEXT, 
    NOTICE_DAYS INTEGER, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    agreementStartDate TEXT, 
    agreementEndDate TEXT,
);


CREATE TABLE ClientStatementPurchasesSnapshot (
    StatementID LONG, 
    Type LONG, 
    MY_ID TEXT, 
    SplitID LONG, 
    TransactionID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    SupplierID TEXT, 
    TranDate DATETIME, 
    NOMINAL_CODE TEXT, 
    PaymentDescription TEXT, 
    PaymentRef TEXT, 
    NetAmount UNKNOWN, 
    VATAmount UNKNOWN, 
    PaymentAmount UNKNOWN, 
    CreditAmount UNKNOWN, 
    OSAmount UNKNOWN, 
    isManagementFee BIT,
);


CREATE TABLE ConsolidatedBankList (
    conBankID LONG, 
    BankCode TEXT, 
    BankName TEXT, 
    BankACNumber TEXT, 
    SortCode TEXT, 
    StatementDate TEXT, 
    ClosingBal UNKNOWN, 
    SOB UNKNOWN,
);


CREATE TABLE Contacts (
    ContactID TEXT, 
    WhosContact TEXT, 
    HeadContact TEXT, 
    ContactName TEXT, 
    CompanyName TEXT, 
    OfficeAddressLine1 TEXT, 
    OfficeAddressLine2 TEXT, 
    OfficeAddressLine3 TEXT, 
    OfficeAddressLine4 TEXT, 
    OfficePostCode TEXT, 
    OfficeTel TEXT, 
    OfficeEmail TEXT, 
    OfficeMobile TEXT, 
    Mobile TEXT, 
    PersonalEmail TEXT, 
    AddressLine1 TEXT, 
    AddressLine2 TEXT, 
    AddressLine3 TEXT, 
    AddressLine4 TEXT, 
    PostCode TEXT, 
    HomeTel TEXT,
);


CREATE TABLE CSPurchasesHistory (
    StatementID LONG, 
    Type LONG, 
    MY_ID TEXT, 
    SplitID LONG, 
    TransactionID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    SupplierID TEXT, 
    TranDate DATETIME, 
    NOMINAL_CODE TEXT, 
    PaymentDescription TEXT, 
    PaymentRef TEXT, 
    NetAmount UNKNOWN, 
    VATAmount UNKNOWN, 
    PaymentAmount UNKNOWN, 
    CreditAmount UNKNOWN, 
    OSAmount UNKNOWN, 
    isManagementFee BIT, 
    isHistoric BIT,
);


CREATE TABLE DemandRecords (
    DemandID LONG, 
    BatchID LONG, 
    SageAccountNumber TEXT, 
    TenantCompanyName TEXT, 
    UnitNumber TEXT, 
    Source INTEGER, 
    TransactionType UNKNOWN, 
    IssueDate DATETIME, 
    SageText TEXT, 
    IsPrinted BIT, 
    SendToPrint BIT, 
    UPDATE_SAGE BIT, 
    ExportedToExcel BIT, 
    DemandHistory BIT, 
    SAGEPostingNumber LONG, 
    CatagoryCode LONG, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    LeaseRef TEXT, 
    AdjTag TEXT, 
    Details TEXT, 
    GenerateDemand TEXT, 
    DmdSlNo LONG, 
    SuppText1 TEXT, 
    SentByEmail UNKNOWN, 
    SentStName TEXT, 
    PostingDate DATETIME, 
    EditRecord BIT, 
    SO BIT, 
    UserID TEXT, 
    SystemID TEXT, 
    DateTimeStamp DATETIME, 
    Module TEXT, 
    UserSessionID TEXT, 
    WindowsUserName TEXT, 
    MachineName TEXT, 
    PrestigeUserName TEXT, 
    ServerIPaddress TEXT, 
    ReportNetAmount UNKNOWN, 
    ReportVATAmount UNKNOWN, 
    ReportReceivedAmount UNKNOWN, 
    ReportDateFrom DATETIME, 
    ReportDateTo DATETIME, 
    ReportDemandTypeDesc TEXT, 
    ReportCreditAmount UNKNOWN, 
    ReportOSAmount UNKNOWN, 
    exclCRNtoCS BIT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME, 
    ClientID4 TEXT, 
    PropertyID4 TEXT,
);


CREATE TABLE DemandRecPreview (
    DemandID LONG, 
    BatchID LONG, 
    SageAccountNumber TEXT, 
    TenantCompanyName TEXT, 
    UnitNumber TEXT, 
    Source INTEGER, 
    TransactionType UNKNOWN, 
    IssueDate DATETIME, 
    SageText TEXT, 
    IsPrinted BIT, 
    SendToPrint BIT, 
    UPDATE_SAGE BIT, 
    ExportedToExcel BIT, 
    DemandHistory BIT, 
    SAGEPostingNumber LONG, 
    CatagoryCode LONG, 
    spare1 LONG, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    LeaseRef TEXT,
);


CREATE TABLE DemandSplitRecords (
    DSR TEXT, 
    SplitID INTEGER, 
    DemandID LONG, 
    A_M TEXT, 
    NominalCodeforAmount TEXT, 
    NominalNameforAmount TEXT, 
    NominalCodeforVAT TEXT, 
    NominalNameforVAT TEXT, 
    NominalCodeforTotal TEXT, 
    NominalNameforTotal TEXT, 
    Amount DOUBLE, 
    VATAmount DOUBLE, 
    TotalAmount DOUBLE, 
    SageRef TEXT, 
    DueDate DATETIME, 
    VATMonth INTEGER, 
    TypeOfDemand INTEGER, 
    Description TEXT, 
    DemandStatement BIT, 
    VAT_CODE INTEGER, 
    DateFrom DATETIME, 
    DateTo DATETIME, 
    TrfReceipt BIT, 
    SAGEPostingNumber LONG, 
    SageDepartment LONG, 
    MFCharged BIT, 
    FrequencyID INTEGER, 
    ChargingFigure UNKNOWN, 
    AdiComment MEMO, 
    ChargingMethod UNKNOWN, 
    JobID TEXT, 
    ReportNetAmountS UNKNOWN, 
    ReportVATAmountS UNKNOWN, 
    ReportReceivedAmountS UNKNOWN, 
    ReportCreditAmountS UNKNOWN, 
    reportOSAmountS UNKNOWN, 
    ReportDateFromS DATETIME, 
    ReportDateToS DATETIME, 
    ReportDemandTypeDescS TEXT, 
    ReportCsShowFlag TEXT, 
    ReportClientID TEXT, 
    ReportPropertyID TEXT, 
    ReportSAGEAC TEXT, 
    ReportTransactionID LONG, 
    ReportTransactionNo TEXT, 
    OSAmount UNKNOWN, 
    ClientID5 TEXT,
);


CREATE TABLE DemandSplPreview (
    DSR TEXT, 
    SplitID INTEGER, 
    DemandID LONG, 
    A_M TEXT, 
    NominalCodeforAmount TEXT, 
    NominalNameforAmount TEXT, 
    NominalCodeforVAT TEXT, 
    NominalNameforVAT TEXT, 
    NominalCodeforTotal TEXT, 
    NominalNameforTotal TEXT, 
    Amount DOUBLE, 
    VATAmount DOUBLE, 
    TotalAmount DOUBLE, 
    SageRef TEXT, 
    DueDate DATETIME, 
    VATMonth INTEGER, 
    TypeOfDemand LONG, 
    Description TEXT, 
    DemandStatement BIT, 
    VAT_CODE INTEGER, 
    DateFrom DATETIME, 
    DateTo DATETIME, 
    TrfReceipt BIT, 
    SAGEPostingNumber LONG, 
    SageDepartment TEXT, 
    MFCharged BIT, 
    FrequencyID INTEGER, 
    LChildsRef TEXT,
);


CREATE TABLE DemandTypes (
    ID INTEGER, 
    Type TEXT, 
    InvCrd TEXT, 
    Prefix TEXT, 
    NominalCodeforAmount TEXT, 
    NominalNameforAmount TEXT, 
    NominalCodeforVAT TEXT, 
    NominalNameforVAT TEXT, 
    NominalCodeforTotal TEXT, 
    NominalNameforTotal TEXT, 
    TransactionType UNKNOWN, 
    CategoryCode UNKNOWN, 
    PaymentDates UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    DTGroup INTEGER, 
    DemandReportName TEXT, 
    PropertyID TEXT, 
    EmailInvoiceTemplate TEXT, 
    ULC BIT, 
    StatementTemplate TEXT, 
    Consolidated BIT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE FinancialYear (
    FYrID TEXT, 
    ClientID TEXT, 
    FinancialYear TEXT, 
    FY_Description TEXT, 
    PeriodsCount SINGLE, 
    Freq TEXT, 
    FY_StDate DATETIME, 
    FY_EndDate DATETIME, 
    Status BIT, 
    Basis TEXT, 
    setascurrent BIT,
);


CREATE TABLE Frequencies (
    ID INTEGER, 
    Frequency TEXT, 
    CalDays TEXT, 
    PartOfYear INTEGER, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE Fund (
    FundID LONG, 
    FundName TEXT, 
    CategoryCode UNKNOWN, 
    SelFund TEXT, 
    szFundID TEXT, 
    FundList TEXT, 
    SelInFund TEXT, 
    FUNDCode TEXT, 
    RRR TEXT,
);


CREATE TABLE FundMatrix (
    ID LONG, 
    ClientId TEXT, 
    PropertyID TEXT, 
    FundID DOUBLE, 
    FundName TEXT, 
    FundCategory TEXT, 
    FundCode TEXT, 
    isDeleted BIT,
);


CREATE TABLE GlobalData (
    PropertyID TEXT, 
    TotalArea LONG, 
    TotalSC DOUBLE, 
    SCperSqFoot DOUBLE, 
    SCYearEnd DATETIME, 
    BaseInterestRate DOUBLE, 
    VATRate INTEGER, 
    VATpercentage DOUBLE, 
    QuarterlyDueDate1 TEXT, 
    QuarterlyDueDate2 TEXT, 
    QuarterlyDueDate3 TEXT, 
    QuarterlyDueDate4 TEXT, 
    HalfYearlyDueDate1 TEXT, 
    HalfYearlyDueDate2 TEXT, 
    YearlyDueDate TEXT, 
    NoOfDaysToSendDemandsB4Due INTEGER, 
    GlobalBankCode TEXT, 
    MonthlyDueDate1 TEXT, 
    MonthlyDueDate2 TEXT, 
    MonthlyDueDate3 TEXT, 
    MonthlyDueDate4 TEXT, 
    MonthlyDueDate5 TEXT, 
    MonthlyDueDate6 TEXT, 
    MonthlyDueDate7 TEXT, 
    MonthlyDueDate8 TEXT, 
    MonthlyDueDate9 TEXT, 
    MonthlyDueDate10 TEXT, 
    MonthlyDueDate11 TEXT, 
    MonthlyDueDate12 TEXT, 
    YearlyInsurance DOUBLE, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    spare9 TEXT, 
    spare10 TEXT, 
    spare11 TEXT, 
    spare12 TEXT, 
    StPath TEXT, 
    vatOptionEnabled LONG, 
    QDueDate1 TEXT, 
    QDueDate2 TEXT, 
    QDueDate3 TEXT, 
    QDueDate4 TEXT, 
    HYDueDate1 TEXT, 
    HYDueDate2 TEXT, 
    MDueDate1 TEXT, 
    MDueDate2 TEXT, 
    MDueDate3 TEXT, 
    MDueDate4 TEXT, 
    MDueDate5 TEXT, 
    MDueDate6 TEXT, 
    MDueDate7 TEXT, 
    MDueDate8 TEXT, 
    MDueDate9 TEXT, 
    MDueDate10 TEXT, 
    MDueDate11 TEXT, 
    MDueDate12 TEXT, 
    YDueDate TEXT, 
    NoOfDaysToSendMFB4Due LONG, 
    chkProduceVatReturn BIT, 
    TaxBasis TEXT, 
    LastCompletedTaxReturnDate DATETIME, 
    TaxInterval LONG, 
    CurrentTaxPeriod DATETIME, 
    isAgentToSubmit BIT,
);


CREATE TABLE GlobalInsurance (
    ID LONG, 
    PropertyID TEXT, 
    DemandType UNKNOWN, 
    FundType UNKNOWN, 
    Amount UNKNOWN, 
    Spare1 TEXT, 
    Spare2 TEXT, 
    PPSF UNKNOWN, 
    SCArea SINGLE, 
    FinancialYear TEXT,
);


CREATE TABLE GlobalRC (
    BudgetID TEXT, 
    PropertyID TEXT, 
    Fund TEXT, 
    TotalBudget UNKNOWN, 
    SCArea SINGLE, 
    PPSF UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    FinancialYear TEXT,
);


CREATE TABLE GlobalSC (
    BudgetID TEXT, 
    PropertyID TEXT, 
    Fund LONG, 
    TotalBudget UNKNOWN, 
    SCArea SINGLE, 
    PPSF UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    FinancialYear TEXT, 
    SCYearEndGenerated BIT,
);


CREATE TABLE GlobalSCDtls (
    BudgetDtlID TEXT, 
    BudgetID TEXT, 
    NC TEXT, 
    NN TEXT, 
    BudgetAmt UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT,
);


CREATE TABLE InterestRates (
    RateID LONG, 
    PropertyID TEXT, 
    DateFrom DATETIME, 
    BaseRate SINGLE, 
    AdditionalRate SINGLE, 
    Active BIT, 
    RateDescription TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT,
);


CREATE TABLE Landlord (
    LandlordID TEXT, 
    LandlordName TEXT, 
    LandlordAddressLine1 TEXT, 
    LandlordAddressLine2 TEXT, 
    LandlordAddressLine3 TEXT, 
    LandlordAddressLine4 TEXT, 
    LandlordPostCode TEXT, 
    LandlordOfficeEmail TEXT, 
    LandlordPersonalEmail TEXT, 
    LandlordHomeTel TEXT, 
    LandlordMobile TEXT, 
    LandlordOfficeAddressLine1 TEXT, 
    LandlordOfficeAddressLine2 TEXT, 
    LandlordOfficeAddressLine3 TEXT, 
    LandlordOfficeAddressLine4 TEXT, 
    LandlordOfficePostCode TEXT, 
    LandlordOfficeTel TEXT, 
    LandlordMemo MEMO, 
    LandLordSageCustAC TEXT, 
    LandLordSageSuppAC TEXT, 
    BANK_ID TEXT, 
    CommissionType UNKNOWN, 
    CommissionAmt INTEGER, 
    BGRPayable UNKNOWN, 
    VATReg TEXT, 
    AcBalance UNKNOWN, 
    Residency TEXT, 
    YearEndDate DATETIME, 
    PaymentMethod TEXT, 
    BacsRef TEXT, 
    HomeOfficeAdd BIT, 
    CompReg TEXT, 
    RegAdd1 TEXT, 
    RegAdd2 TEXT, 
    RegAdd3 TEXT, 
    RegPostCode TEXT, 
    StToLandlordAddress LONG, 
    StToStatementAddress LONG, 
    StLandlordHomeTel TEXT, 
    StLandlordHomeEmail TEXT, 
    StLandlordOfficeTel TEXT, 
    StLandlordStatementEmail TEXT, 
    StLandlordMobile TEXT, 
    StLandlordStatementHometel TEXT, 
    StLandlordOfficeEmail TEXT,
);


CREATE TABLE LeaseAssignments (
    AssignmentID LONG, 
    LeaseID TEXT, 
    AssignDate TEXT, 
    Assignee TEXT, 
    Decp TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT,
);


CREATE TABLE LeaseBreaches (
    BreachID LONG, 
    LeaseID TEXT, 
    BreachType TEXT, 
    CommenceDate DATETIME, 
    InitiatedBy TEXT, 
    Resolved BIT, 
    DateReceived DATETIME, 
    ReceivedBy TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    DeleteFlag TEXT, 
    LeaseMemo MEMO,
);


CREATE TABLE LeaseDetails (
    LeaseID TEXT, 
    HeadLease TEXT, 
    SageAccountNumber TEXT, 
    CompanyName TEXT, 
    UnitNumber TEXT, 
    StartDate DATETIME, 
    EndDate DATETIME, 
    YearEnd DATETIME, 
    SCPayable TEXT, 
    SCAnnual DOUBLE, 
    SCTotal DOUBLE, 
    SCAmount DOUBLE, 
    SCTOLimit DOUBLE, 
    ServiceChargeDept TEXT, 
    InterestChargeable TEXT, 
    DaysAfterInterestPayable INTEGER, 
    AdditionalInterest DOUBLE, 
    InterestChargedOn DOUBLE, 
    InterestAmount DOUBLE, 
    IntDemandType UNKNOWN, 
    IntChargeDept TEXT, 
    BreakClause TEXT, 
    BreakType TEXT, 
    BreakDate DATETIME, 
    DateFlagDate DATETIME, 
    DateFlagDescription TEXT, 
    TypeOfStore TEXT, 
    Notes TEXT, 
    BRPayable TEXT, 
    RentReviewDate DATETIME, 
    RentIncreaseAmount DOUBLE, 
    RentChargeDept TEXT, 
    InsurancePayable TEXT, 
    Text1 TEXT, 
    Text2 TEXT, 
    Text3 TEXT, 
    SuppCaption1 TEXT, 
    SuppCaption2 TEXT, 
    SuppCaption3 TEXT, 
    Status BIT, 
    OLED BIT, 
    TerminateDate DATETIME, 
    HoldingOver BIT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    UtilityUsage TEXT, 
    Usage TEXT, 
    ALARM TEXT, 
    REMINDER_ID TEXT, 
    SuppText1 TEXT, 
    SuppText2 TEXT, 
    SuppText3 TEXT, 
    DateFlagDt2 TEXT, 
    DateFlagDt3 TEXT, 
    DateFlagDescription2 TEXT, 
    DateFlagDescription3 TEXT, 
    LeaseValue UNKNOWN, 
    GPrataDmd BIT, 
    CapAmount DOUBLE, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE LeaseHistory (
    HistoryID TEXT, 
    LeaseID TEXT, 
    SageAccountNumber TEXT, 
    UnitNumber TEXT, 
    StartDate DATETIME, 
    EndDate DATETIME, 
    YearEnd DATETIME, 
    SCPayable TEXT, 
    InterestChargeable TEXT, 
    DaysAfterInterestPayable INTEGER, 
    AdditionalInterest DOUBLE, 
    InterestChargedOn DOUBLE, 
    InterestAmount DOUBLE, 
    IntDemandType UNKNOWN, 
    IntChargeDept TEXT, 
    BRPayable TEXT, 
    RentIncreaseAmount DOUBLE, 
    TypeOfStore TEXT, 
    InsurancePayable TEXT, 
    Status BIT, 
    OLED BIT, 
    TerminateDate DATETIME, 
    HoldingOver BIT, 
    UtilityUsage TEXT, 
    Usage TEXT, 
    ALARM TEXT, 
    REMINDER_ID TEXT, 
    LeaseValue UNKNOWN, 
    GPrataDmd BIT,
);


CREATE TABLE LInsuranceCharges (
    InsCharges TEXT, 
    LeaseID TEXT, 
    InsuranceStartDate DATETIME, 
    InsuranceFrequency LONG, 
    InsuranceEndDate DATETIME, 
    InsuranceDemandType INTEGER, 
    InsuranceEachPeriod DOUBLE, 
    InsuranceNextDueDate DATETIME, 
    ChargingType UNKNOWN, 
    ChargingFigure DOUBLE, 
    TotalYearlyInsurance DOUBLE, 
    InsuranceDept LONG, 
    InsDesc TEXT, 
    StopIC TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    FDD TEXT, 
    StopAutoDmd BIT, 
    GPD BIT,
);


CREATE TABLE LRentCharges (
    RentCharges TEXT, 
    LeaseID TEXT, 
    RentChargeDept TEXT, 
    BRFrequency INTEGER, 
    BRStartDate DATETIME, 
    BRNextDueDate DATETIME, 
    BRTotal DOUBLE, 
    BRAmount DOUBLE, 
    BRDemandType INTEGER, 
    RentDesc TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    StopRC TEXT, 
    StopByRR TEXT, 
    RR_ID LONG, 
    PRR UNKNOWN, 
    FDD TEXT, 
    StopAutoDmd BIT, 
    GPD BIT, 
    RRTotal DOUBLE, 
    RRAmount DOUBLE, 
    RRPrint TEXT,
);


CREATE TABLE LServiceCharges (
    ServiceCharge TEXT, 
    LeaseID TEXT, 
    SCFrequency INTEGER, 
    SCPayableFrom DATETIME, 
    SCNextDueDate DATETIME, 
    ChargingMethod UNKNOWN, 
    CMFigure DOUBLE, 
    SCTotal DOUBLE, 
    SCAmount DOUBLE, 
    SCTOLimit DOUBLE, 
    SCDemandType INTEGER, 
    ServiceChargeDept TEXT, 
    SCDesc TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    StopSC TEXT, 
    ScheduleID LONG, 
    FDD TEXT, 
    StopAutoDmd BIT, 
    GPD BIT, 
    SCYE BIT, 
    SCYEDate DATETIME,
);


CREATE TABLE LUtilityUsage (
    UtilityUsage TEXT, 
    LeaseID TEXT, 
    UtilityType TEXT, 
    Description TEXT, 
    CurrentReading TEXT, 
    ReadingDate DATETIME, 
    DueDate DATETIME, 
    Usage TEXT, 
    Amount UNKNOWN, 
    Balance UNKNOWN, 
    IsGenerated BIT, 
    BF BIT, 
    LatestReading BIT, 
    DemandType UNKNOWN, 
    Fund UNKNOWN, 
    DateFrom DATETIME, 
    DateTo DATETIME,
);


CREATE TABLE ManagementFee (
    PI_ActualID TEXT, 
    SRSlNumber LONG, 
    ReceiptSLNumber LONG, 
    ReceiptType DOUBLE, 
    ChargingMethod TEXT, 
    SageAccountNumber TEXT, 
    ReceiptTypeDescription TEXT, 
    PropertyID TEXT, 
    FundID DOUBLE, 
    RptAmtType TEXT, 
    ExtRef TEXT, 
    ChargeDate DATETIME, 
    ReceiptDate DATETIME, 
    ReceiptTransactionID LONG, 
    ReceiptSplitID LONG, 
    ReceiptAmount UNKNOWN, 
    AgrPercentage UNKNOWN, 
    MgtFeeAmt UNKNOWN, 
    VATPercentage UNKNOWN, 
    VAT UNKNOWN, 
    MgtFeeAmtTotal UNKNOWN,
);


CREATE TABLE ManagementFeePreview (
    PI_ActualID TEXT, 
    SRSlNumber LONG, 
    ReceiptSLNumber LONG, 
    ReceiptType DOUBLE, 
    ChargingMethod TEXT, 
    SageAccountNumber TEXT, 
    ReceiptTypeDescription TEXT, 
    PropertyID TEXT, 
    FundID DOUBLE, 
    RptAmtType TEXT, 
    ExtRef TEXT, 
    ChargeDate DATETIME, 
    ReceiptDate DATETIME, 
    ReceiptTransactionID LONG, 
    ReceiptSplitID LONG, 
    ReceiptAmount UNKNOWN, 
    AgrPercentage UNKNOWN, 
    MgtFeeAmt UNKNOWN, 
    VATPercentage UNKNOWN, 
    VAT UNKNOWN, 
    MgtFeeAmtTotal UNKNOWN,
);


CREATE TABLE MemoDetails (
    MemoID DOUBLE, 
    MemoType TEXT, 
    SageAccountNumber TEXT, 
    MemoDescription MEMO, 
    userName TEXT, 
    UpdateTime DATETIME,
);


CREATE TABLE NJ_CC (
    RecordID LONG, 
    ClientID TEXT, 
    Code TEXT, 
    CC TEXT,
);


CREATE TABLE NJ_Header (
    RecordID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    NJDate DATETIME, 
    NJTitle TEXT, 
    History BIT, 
    Posted BIT, 
    PrintThis BIT, 
    PostingDate DATETIME, 
    DateTimeStamp TEXT, 
    Module TEXT, 
    UserSessionID TEXT, 
    WindowsUserName TEXT, 
    MachineName TEXT, 
    PrestigeUserName TEXT, 
    ServerIPaddress TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE NJ_Split (
    RecordID TEXT, 
    ParentID LONG, 
    NC TEXT, 
    SpLineDes TEXT, 
    FundID LONG, 
    TYPE_ID UNKNOWN, 
    NetAmt UNKNOWN, 
    VAT_CODE TEXT, 
    VATAmt UNKNOWN, 
    TotalAmt UNKNOWN,
);


CREATE TABLE NLCategory (
    CategoryCode TEXT, 
    CategoryName TEXT,
);


CREATE TABLE NLPOSTING (
    THIS_RECORD TEXT, 
    PARENT_RECORD TEXT, 
    TRANS_ID TEXT, 
    UNIQUE_REFERENCE_NO LONG, 
    POSTED_DATE DATETIME, 
    TRANSACTION_DATE DATETIME, 
    TRANSACTION_TYPE LONG, 
    ACCOUNT_NUMBER TEXT, 
    PROPERTY_ID TEXT, 
    UNIT_ID TEXT, 
    JOB_NO TEXT, 
    FUND_ID LONG, 
    SCHEDULE_ID LONG, 
    AMOUNT UNKNOWN, 
    REFERENCE TEXT, 
    NOMINAL_CODE TEXT, 
    TRANSACTION_DESCRIPTION TEXT, 
    VAT_PERIOD_END_DT UNKNOWN, 
    YEAR_END_CLOSED BIT, 
    USER_NUMBER TEXT, 
    VAT_RECON BIT, 
    AMOUNT_TYPE TEXT, 
    ClientID TEXT, 
    DeleteFlag BIT, 
    TRANSACTION_REF TEXT, 
    SplitID LONG, 
    isManualEdit BIT, 
    CreatedAt DATETIME, 
    CreatedBy TEXT,
);


CREATE TABLE NLSubTypes (
    STCode TEXT, 
    STName TEXT, 
    STDescription TEXT,
);


CREATE TABLE NLType (
    NLTypeCode LONG, 
    TypeValue TEXT,
);


CREATE TABLE NominalLedger (
    Code TEXT, 
    Name TEXT, 
    CategoryCode TEXT, 
    Type LONG, 
    Debit UNKNOWN, 
    Credit UNKNOWN, 
    DrCr TEXT, 
    TypeIE TEXT, 
    ClientID TEXT, 
    Posting BIT, 
    SubType TEXT, 
    CAName TEXT, 
    CAFixed BIT, 
    CADisOrder SINGLE, 
    CAPosting BIT, 
    CAType TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE PayableTypes (
    ID UNKNOWN, 
    PayType TEXT, 
    PayIC TEXT, 
    PaySagePrefix TEXT, 
    PayNCAmt TEXT, 
    PayNNAmt TEXT, 
    PayNCVat TEXT, 
    PayNNVat TEXT, 
    PayNCTotal TEXT, 
    PayNNTotal TEXT, 
    TransactionType UNKNOWN, 
    CategoryCode UNKNOWN, 
    PaymentDates UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    propertyID TEXT, 
    ClientID TEXT, 
    GroupID LONG, 
    isUseControlAccount BIT, 
    PrintTemplate TEXT, 
    EmailTemplate TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE PaymentDates (
    DateSetID UNKNOWN, 
    NameOfSet TEXT, 
    MonthlyDueDate1 TEXT, 
    MonthlyDueDate2 TEXT, 
    MonthlyDueDate3 TEXT, 
    MonthlyDueDate4 TEXT, 
    MonthlyDueDate5 TEXT, 
    MonthlyDueDate6 TEXT, 
    MonthlyDueDate7 TEXT, 
    MonthlyDueDate8 TEXT, 
    MonthlyDueDate9 TEXT, 
    MonthlyDueDate10 TEXT, 
    MonthlyDueDate11 TEXT, 
    MonthlyDueDate12 TEXT, 
    QuarterlyDueDate1 TEXT, 
    QuarterlyDueDate2 TEXT, 
    QuarterlyDueDate3 TEXT, 
    QuarterlyDueDate4 TEXT, 
    HalfYearlyDueDate1 TEXT, 
    HalfYearlyDueDate2 TEXT, 
    YearlyDueDate TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT,
);


CREATE TABLE PayTransactions (
    TransactionID LONG, 
    TranType TEXT, 
    Alloc_Unalloc UNKNOWN, 
    FromTran LONG, 
    ToTran LONG, 
    AllocDate DATETIME, 
    PaymentAmount UNKNOWN, 
    Discount UNKNOWN, 
    IsSageUpdate BIT, 
    UpdateSage BIT, 
    Unalloc LONG, 
    BankCode TEXT, 
    NominalCode TEXT, 
    Exp2Sage TEXT, 
    Reconciled UNKNOWN, 
    ReconNow TEXT, 
    SlNumber LONG, 
    FundID LONG, 
    VATAMOUNT UNKNOWN, 
    NetAmount UNKNOWN, 
    VAT_PERIOD_END_DATE DATETIME, 
    DeleteFlag BIT, 
    SplitIDofPI LONG, 
    ClientID TEXT, 
    PIOrPPR TEXT, 
    PPOrPAOrPC TEXT, 
    PaymentSAGEAC TEXT, 
    ClientID2 TEXT,
);


CREATE TABLE PayTransactionsSplit (
    TransactionID LONG, 
    TranType TEXT, 
    Alloc_Unalloc DOUBLE, 
    FromTran LONG, 
    ToTran LONG, 
    Allocdate DATETIME, 
    PaymentAmount UNKNOWN, 
    BankCode TEXT, 
    NominalCode TEXT, 
    FundID LONG, 
    NetAmount UNKNOWN, 
    VATAMOUNT UNKNOWN, 
    VAT_PERIOD_END_DATE DATETIME, 
    SplitIDofPI LONG, 
    DeleteFlag BIT, 
    ClientID2 TEXT,
);


CREATE TABLE Periods (
    PeriodID TEXT, 
    FYrID TEXT, 
    Period TEXT, 
    Period_Descp TEXT, 
    P_StDate DATETIME, 
    P_EndDate DATETIME, 
    Status BIT, 
    Transactions BIT,
);


CREATE TABLE POrders (
    MY_ID TEXT, 
    SlNumber LONG, 
    SupplierID TEXT, 
    Q_DATE DATETIME, 
    Exp_DATE DATETIME, 
    OrderType UNKNOWN, 
    PI_ID TEXT, 
    Status BIT, 
    TOTAL_AMOUNT UNKNOWN, 
    History BIT, 
    ClientID TEXT, 
    PropertyID TEXT,
);


CREATE TABLE PrimaryCode (
    Code TEXT, 
    Value TEXT, 
    Description TEXT, 
    Flexible BIT,
);


CREATE TABLE Property (
    ClientID TEXT, 
    PropertyID TEXT, 
    PropertyName TEXT, 
    ProAddressLine1 TEXT, 
    ProAddressLine2 TEXT, 
    ProAddressLine3 TEXT, 
    ProAddressLine4 TEXT, 
    ProPostCode TEXT, 
    TotalArea DOUBLE, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    DeptNumber INTEGER, 
    Landlord TEXT, 
    Manager TEXT, 
    ContactDetails TEXT, 
    SuppCaption1 TEXT, 
    SuppCaption2 TEXT, 
    SuppCaption3 TEXT, 
    SuppText1 TEXT, 
    SuppText2 TEXT, 
    SuppText3 TEXT, 
    DateFlagDt1 TEXT, 
    DateFlagDt2 TEXT, 
    DateFlagDt3 TEXT, 
    DateFlagDescription1 TEXT, 
    DateFlagDescription2 TEXT, 
    DateFlagDescription3 TEXT, 
    RCC TEXT, 
    RAS TEXT, 
    CBY TEXT, 
    RunningAutoDemand TEXT, 
    MemoText MEMO, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE PropertyAnalysis (
    PropertyAnalysisID LONG, 
    PropertyID TEXT, 
    AnalysisType TEXT, 
    AnalysisDescription TEXT, 
    AnalysisOption TEXT, 
    AnalysisValue DOUBLE, 
    AnalysisQuantity DOUBLE, 
    AnalysisPercentage DOUBLE, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    Reference TEXT, 
    AnalysisValue1 DOUBLE,
);


CREATE TABLE PropertyInsurance (
    PropertyInsuranceID TEXT, 
    PropertyID TEXT, 
    Insurer TEXT, 
    InsuranceType TEXT, 
    PolicyNo TEXT, 
    SumInsured DOUBLE, 
    AnnualPR DOUBLE, 
    MonthlyPR DOUBLE, 
    ExpiryDate DATETIME, 
    RechargeableAmount DOUBLE, 
    RechargeableFreq TEXT, 
    InsContact TEXT, 
    Telephone TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    StartDate TEXT, 
    Comments TEXT, 
    Attachment TEXT, 
    Module TEXT, 
    Usage TEXT,
);


CREATE TABLE PropertyLandlord (
    PropertyID TEXT, 
    LandlordID TEXT, 
    Status LONG,
);


CREATE TABLE PropertyMaintHistory (
    ID TEXT, 
    PropertyID TEXT, 
    MaintenanceType TEXT, 
    ReportedDate DATETIME, 
    DateCompleted DATETIME, 
    TaskOwner TEXT, 
    RemindDate DATETIME, 
    Alarm BIT, 
    REMINDER_ID TEXT, 
    Job_DiaryName TEXT, 
    AssignedIL TEXT, 
    AssignedTo TEXT, 
    ReportedIS TEXT, 
    ReportedBy TEXT, 
    ExpectedStartDate TEXT, 
    ExpectedCompletionDate TEXT, 
    Detail MEMO, 
    BudgetCost UNKNOWN, 
    ActualCost UNKNOWN, 
    RecordType TEXT, 
    RemindTime TEXT, 
    Location TEXT, 
    Urgent TEXT, 
    Instruction MEMO, 
    ReportedFrom TEXT, 
    FundID LONG, 
    OverrideBudget BIT, 
    FYrID TEXT, 
    BudgetPassed BIT, 
    UnitNumber TEXT, 
    LastModified TEXT, 
    ModifiedBy TEXT,
);


CREATE TABLE PropertySafety (
    PropertySafetyID LONG, 
    PropertyID TEXT, 
    SafetyType TEXT, 
    SafetyInspection TEXT, 
    NextDueDate DATETIME, 
    SafetyStatus TEXT, 
    InspectedBy TEXT, 
    SafetyTelephone TEXT, 
    Certificate BIT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT,
);


CREATE TABLE PropertyUtilities (
    PropertyUtilitiesID LONG, 
    PropertyID TEXT, 
    Authority_Supplier TEXT, 
    UtilitiesType TEXT, 
    UtilitiesReference TEXT, 
    ChargeRate DOUBLE, 
    UtilitiesTelephone TEXT, 
    FinalReading TEXT, 
    DateVacated DATETIME, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    Occupier TEXT, 
    Status TEXT, 
    StartDate TEXT, 
    InitialReading TEXT, 
    Comments TEXT, 
    Module TEXT,
);


CREATE TABLE RecordLocking (
    SCREEN TEXT, 
    WorkStation TEXT, 
    USER TEXT, 
    TableName TEXT, 
    ClientID TEXT, 
    BankCode TEXT,
);


CREATE TABLE RentAnalysis (
    ID LONG, 
    LeaseID TEXT, 
    SerialNumber TEXT, 
    RentReviewDate DATETIME, 
    RentIncreaseDate DATETIME, 
    RentIncreaseAmount UNKNOWN, 
    REMINDER_ID TEXT, 
    Comments TEXT, 
    RRDemandType LONG, 
    Status TEXT, 
    RRStatus TEXT,
);


CREATE TABLE RentSummaryStatement (
    StatementID DOUBLE, 
    statementNo DOUBLE, 
    ClientIDLandlordID TEXT, 
    BankCode TEXT, 
    PreviousStatementDate DATETIME, 
    StatementDate DATETIME, 
    StatementOpBal DOUBLE, 
    Retentions DOUBLE, 
    RetenstionDescription TEXT, 
    ClearRetentions BIT, 
    AccrualsAcBalance DOUBLE, 
    SupplierAcBalance DOUBLE, 
    ManagingAgentAcBalance DOUBLE, 
    LandlordACBalance DOUBLE, 
    ClientACBalance DOUBLE, 
    ListOfFundId TEXT, 
    ListOfPayableTypeID TEXT, 
    ListOfinputProperties TEXT, 
    TenantDepositsReceived DOUBLE, 
    AvailableFunds DOUBLE, 
    PaymentsonAccount DOUBLE, 
    PayableAmount DOUBLE, 
    StatementClosingBal DOUBLE, 
    ClientPayments DOUBLE, 
    LandlordPayments DOUBLE, 
    ManagingAgentPayments DOUBLE, 
    TenantReceipts DOUBLE, 
    SupplierPayments DOUBLE, 
    BankPaymentReceipts DOUBLE, 
    ClientLandlordBalance DOUBLE, 
    PINumber TEXT, 
    PITransactionID DOUBLE, 
    Generated_Date DATETIME, 
    Printed BIT, 
    Emailed BIT, 
    Invoiced BIT, 
    PostToHistory BIT, 
    BankPayment DOUBLE, 
    BankReceipts DOUBLE, 
    BankACBalance DOUBLE, 
    ConsolidatedPropID TEXT, 
    StatementNobyProperty LONG, 
    ReportGenID LONG, 
    isConsolidated BIT, 
    isfinalized LONG, 
    DateFinalized DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME, 
    InclSupplierOS BIT, 
    InclMngtFeesDue BIT,
);


CREATE TABLE RentSummaryStatementdetails (
    StatementID LONG, 
    PINumber TEXT, 
    Amount DOUBLE, 
    OSamount DOUBLE, 
    ClientID TEXT, 
    SageAccountNumber TEXT, 
    ID LONG, 
    SplitID LONG, 
    PercentageLL DOUBLE,
);


CREATE TABLE RentSummaryStatementPreview (
    StatementID DOUBLE, 
    statementNo DOUBLE, 
    ClientIDLandlordID TEXT, 
    BankCode TEXT, 
    PreviousStatementDate DATETIME, 
    StatementDate DATETIME, 
    StatementOpBal DOUBLE, 
    Retentions DOUBLE, 
    RetenstionDescription TEXT, 
    ClearRetentions BIT, 
    AccrualsAcBalance DOUBLE, 
    SupplierAcBalance DOUBLE, 
    ManagingAgentAcBalance DOUBLE, 
    LandlordACBalance DOUBLE, 
    ClientACBalance DOUBLE, 
    ListOfFundId TEXT, 
    ListOfPayableTypeID TEXT, 
    ListOfinputProperties TEXT, 
    TenantDepositsReceived DOUBLE, 
    AvailableFunds DOUBLE, 
    PaymentsonAccount DOUBLE, 
    PayableAmount DOUBLE, 
    StatementClosingBal DOUBLE, 
    ClientPayments DOUBLE, 
    LandlordPayments DOUBLE, 
    ManagingAgentPayments DOUBLE, 
    TenantReceipts DOUBLE, 
    SupplierPayments DOUBLE, 
    BankPaymentReceipts DOUBLE, 
    ClientLandlordBalance DOUBLE, 
    PINumber TEXT, 
    PITransactionID DOUBLE, 
    Generated_Date DATETIME, 
    Printed BIT, 
    Emailed BIT, 
    Invoiced BIT, 
    PostToHistory BIT, 
    BankPayment DOUBLE, 
    BankReceipts DOUBLE, 
    BankACBalancePreview DOUBLE,
);


CREATE TABLE ReportAgedCreditor (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    TransactionID LONG, 
    SplitID LONG, 
    SLNumber LONG, 
    SageAccountNumber TEXT, 
    UnitID TEXT, 
    FundID DOUBLE, 
    Type DOUBLE, 
    Details TEXT, 
    Amount UNKNOWN, 
    Amountsign DOUBLE, 
    PDate DATETIME, 
    DDate DATETIME, 
    total UNKNOWN, 
    current UNKNOWN, 
    sixty UNKNOWN, 
    ninety UNKNOWN, 
    ninetyplus UNKNOWN, 
    PostingDate DATETIME, 
    paytranflag BIT, 
    AllocationDate DATETIME, 
    extRef TEXT,
);


CREATE TABLE ReportAgedCreditorSet (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    TransactionID LONG, 
    SplitID LONG, 
    SLNumber LONG, 
    SageAccountNumber TEXT, 
    UnitID TEXT, 
    FundID DOUBLE, 
    Type DOUBLE, 
    Details TEXT, 
    Amount UNKNOWN, 
    Amountsign DOUBLE, 
    PDate DATETIME, 
    DDate DATETIME, 
    total UNKNOWN, 
    current UNKNOWN, 
    sixty UNKNOWN, 
    ninety UNKNOWN, 
    ninetyplus UNKNOWN, 
    PostingDate DATETIME, 
    paytranflag BIT, 
    AllocationDate DATETIME, 
    extRef TEXT, 
    RecordSet LONG,
);


CREATE TABLE ReportAgedCreditorsum (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    SageAccountNumber TEXT, 
    total UNKNOWN, 
    current UNKNOWN, 
    sixty UNKNOWN, 
    ninety UNKNOWN, 
    ninetyplus UNKNOWN,
);


CREATE TABLE ReportBalanceSheet (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    BSType TEXT, 
    ClientID TEXT, 
    Header TEXT, 
    SubHeader TEXT, 
    NominalCode TEXT, 
    Name TEXT, 
    Balance UNKNOWN, 
    Debit UNKNOWN, 
    Credit UNKNOWN,
);


CREATE TABLE ReportBudVsAE (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    NC TEXT, 
    tBalance UNKNOWN, 
    Budget UNKNOWN, 
    Variance UNKNOWN,
);


CREATE TABLE ReportCashbookHistory (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    iRow DOUBLE, 
    TDate DATETIME, 
    No TEXT, 
    tTYpe TEXT, 
    Account TEXT, 
    Reference TEXT, 
    Detail TEXT, 
    Debit UNKNOWN, 
    Credit UNKNOWN, 
    Reconciled TEXT, 
    StDate TEXT,
);


CREATE TABLE ReportCashbookTrans (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    RDate DATETIME, 
    No TEXT, 
    Type UNKNOWN, 
    SageAccount TEXT, 
    Details TEXT, 
    Reference TEXT, 
    Debit UNKNOWN, 
    Credit UNKNOWN, 
    StatementDate TEXT,
);


CREATE TABLE ReportCategory (
    RecordID TEXT, 
    ClientID TEXT, 
    CategoryCode TEXT, 
    CategoryName TEXT, 
    CatDesc TEXT,
);


CREATE TABLE ReportClientHistory (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    SIGN TEXT, 
    transactionID LONG, 
    Type DOUBLE, 
    Type_desc TEXT, 
    PF TEXT, 
    Pdate DATETIME, 
    Details TEXT, 
    extref TEXT, 
    amount UNKNOWN, 
    Osamount UNKNOWN, 
    Balance UNKNOWN, 
    flag DOUBLE, 
    isMaster DOUBLE, 
    ActualINV TEXT, 
    ClientID TEXT, 
    SageAccountNumber TEXT,
);


CREATE TABLE ReportClientStatementDemands (
    StatementID LONG, 
    SITrxID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    DemandID LONG, 
    DemandSLNumber LONG, 
    SplitID LONG, 
    SageAccountNumber TEXT, 
    UnitNumber TEXT, 
    TransactionType LONG, 
    TypeOfDemand LONG, 
    DueDate DATETIME, 
    DateFrom DATETIME, 
    DateTo DATETIME, 
    NetAmount UNKNOWN, 
    VATAmount UNKNOWN, 
    ReceivedAmountS UNKNOWN, 
    CreditAmount UNKNOWN, 
    OSAmount UNKNOWN, 
    BBF UNKNOWN,
);


CREATE TABLE ReportClientStatementDemandsPreview (
    StatementID LONG, 
    SITrxID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    DemandID LONG, 
    DemandSLNumber LONG, 
    SplitID LONG, 
    SageAccountNumber TEXT, 
    UnitNumber TEXT, 
    TransactionType LONG, 
    TypeOfDemand LONG, 
    DueDate DATETIME, 
    DateFrom DATETIME, 
    DateTo DATETIME, 
    NetAmount UNKNOWN, 
    VATAmount UNKNOWN, 
    ReceivedAmountS UNKNOWN, 
    CreditAmount UNKNOWN, 
    OSAmount UNKNOWN,
);


CREATE TABLE ReportClientStatementPurchases (
    StatementID LONG, 
    Type LONG, 
    MY_ID TEXT, 
    SplitID LONG, 
    TransactionID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    SupplierID TEXT, 
    TranDate DATETIME, 
    NOMINAL_CODE TEXT, 
    PaymentDescription TEXT, 
    PaymentRef TEXT, 
    NetAmount UNKNOWN, 
    VATAmount UNKNOWN, 
    PaymentAmount UNKNOWN, 
    CreditAmount UNKNOWN, 
    OSAmount UNKNOWN,
);


CREATE TABLE ReportClientStatementPurchasesPreview (
    StatementID LONG, 
    Type LONG, 
    MY_ID TEXT, 
    SplitID LONG, 
    TransactionID LONG, 
    ClientID TEXT, 
    PropertyID TEXT, 
    SupplierID TEXT, 
    TranDate DATETIME, 
    NOMINAL_CODE TEXT, 
    PaymentDescription TEXT, 
    PaymentRef TEXT, 
    NetAmount UNKNOWN, 
    VATAmount UNKNOWN, 
    PaymentAmount UNKNOWN, 
    CreditAmount UNKNOWN, 
    OSAmount UNKNOWN, 
    isHistoric BIT,
);


CREATE TABLE ReportLAChistory (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    SIGN TEXT, 
    transactionID LONG, 
    Type DOUBLE, 
    Type_desc TEXT, 
    PF TEXT, 
    slnumber LONG, 
    Rdate DATETIME, 
    Details TEXT, 
    extref TEXT, 
    amount UNKNOWN, 
    Osamount UNKNOWN, 
    Balance UNKNOWN, 
    isMaster DOUBLE, 
    SageAccountNumber TEXT, 
    DemandRef1 LONG, 
    ClientID1 TEXT, 
    PropertyID1 TEXT, 
    UnitID1 TEXT, 
    PostingDate1 DATETIME,
);


CREATE TABLE ReportManagingAgentFeesPaid (
    ClientID TEXT, 
    PropertyID TEXT, 
    PI TEXT, 
    TransactionID LONG, 
    InvNo TEXT, 
    TransDate DATETIME, 
    Reference TEXT, 
    Description TEXT, 
    PaidAmount DOUBLE, 
    OsAmount DOUBLE, 
    NET DOUBLE, 
    VAT DOUBLE, 
    Total DOUBLE,
);


CREATE TABLE ReportNLHistory (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    THIS_RECORD TEXT, 
    TRANS_ID TEXT, 
    TRANSACTION_REF TEXT, 
    TRANSACTION_DATE DATETIME, 
    POSTED_DATE DATETIME, 
    UNIQUE_REFERENCE_NO LONG, 
    TRANSACTION_DESCRIPTION TEXT, 
    AMOUNT UNKNOWN, 
    FUND_ID LONG, 
    PROPERTY_ID TEXT, 
    TRANSACTION_TYPE UNKNOWN, 
    AMOUNT_TYPE TEXT, 
    REFERENCE TEXT, 
    ACCOUNT_NUMBER TEXT, 
    FundName TEXT, 
    CONSTANT TEXT, 
    DESCRIPTION TEXT, 
    DEBIT UNKNOWN, 
    CREDIT UNKNOWN, 
    CAFixed TEXT, 
    POSTING TEXT, 
    SplitID LONG, 
    TransID TEXT,
);


CREATE TABLE ReportProfitAndLoss (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    Header TEXT, 
    SubHeader TEXT, 
    NominalCode TEXT, 
    Name TEXT, 
    Balance UNKNOWN, 
    Debit UNKNOWN, 
    Credit UNKNOWN,
);


CREATE TABLE ReportSAChistory (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    SIGN TEXT, 
    transactionID LONG, 
    Type DOUBLE, 
    Type_desc TEXT, 
    PF TEXT, 
    Pdate DATETIME, 
    Details TEXT, 
    extref TEXT, 
    amount UNKNOWN, 
    Osamount UNKNOWN, 
    Balance UNKNOWN, 
    flag DOUBLE, 
    isMaster DOUBLE, 
    ClientID TEXT, 
    ActualINV TEXT,
);


CREATE TABLE ReportSchedule23 (
    ClientID TEXT, 
    ClientName TEXT, 
    ClientADD1 TEXT, 
    ClientADD2 TEXT, 
    ClientADD3 TEXT, 
    ClientADD4 TEXT, 
    PostCode TEXT, 
    FundID LONG, 
    FundName TEXT, 
    Amount UNKNOWN, 
    CurrencyCode TEXT, 
    PropertyID TEXT, 
    PropertyName TEXT, 
    PropertyAddress TEXT, 
    TaxYear TEXT, 
    MAgentID TEXT, 
    MAgentName TEXT, 
    Reference TEXT, 
    NINO TEXT, 
    UTR TEXT, 
    VRN TEXT, 
    BankAccName TEXT, 
    BankSortCode TEXT, 
    BankAccNumber TEXT, 
    EntityEmail TEXT, 
    EntityPhone TEXT, 
    FreeFField1 TEXT, 
    FreeFField2 TEXT, 
    FreeFField3 TEXT,
);


CREATE TABLE ReportSCImport (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    FUNDORNOMINAL TEXT, 
    NOMINALNAME TEXT, 
    FUNDCODE TEXT, 
    NominalCode TEXT, 
    BUDGETAMOUNT TEXT,
);


CREATE TABLE ReportTrialBalance (
    ReportingDate DATETIME, 
    SessionID TEXT, 
    ClientID TEXT, 
    SubHeader TEXT, 
    NominalCode TEXT, 
    Name TEXT, 
    NominalType TEXT, 
    Balance UNKNOWN, 
    Debit UNKNOWN, 
    Credit UNKNOWN,
);


CREATE TABLE ReportViewBankBalance (
    ClientID TEXT, 
    BankCode TEXT, 
    BankName TEXT, 
    Amount UNKNOWN,
);


CREATE TABLE ReportViewBankBalanceReconciled (
    ClientID TEXT, 
    ClientName TEXT, 
    BankAccountName TEXT, 
    BankAccountNumber TEXT, 
    Receipt UNKNOWN, 
    Payment UNKNOWN, 
    LastReconciledDate DATETIME, 
    LastReconciledBankBalance UNKNOWN, 
    LastReconciledStatementBalance UNKNOWN, 
    UnreconciledCashBookBalance UNKNOWN, 
    CashbookcurrentBalance UNKNOWN,
);


CREATE TABLE RetentionDetails (
    StatementID DOUBLE, 
    SlNumber DOUBLE, 
    Description TEXT, 
    amount DOUBLE, 
    isCleared BIT, 
    ClientID TEXT, 
    Reference TEXT, 
    RDate DATETIME, 
    PropertyID TEXT, 
    isHist BIT, 
    FUNDID LONG, 
    ID LONG, 
    isDeleted BIT, 
    isPrint BIT, 
    BankCode TEXT,
);


CREATE TABLE RetentionDetailsPrev (
    StatementID DOUBLE, 
    SlNumber DOUBLE, 
    Description TEXT, 
    amount DOUBLE, 
    isCleared BIT, 
    ClientID TEXT,
);


CREATE TABLE RptTransactions (
    TranType TEXT, 
    TransactionID LONG, 
    Alloc_Unalloc UNKNOWN, 
    FromTran LONG, 
    ToTran LONG, 
    AllocDate DATETIME, 
    ReceiptAmount UNKNOWN, 
    Discount UNKNOWN, 
    IsSageUpdate BIT, 
    UpdateSage BIT, 
    Unalloc LONG, 
    BankCode TEXT, 
    NominalCode TEXT, 
    SlNumber LONG, 
    Reconciled UNKNOWN, 
    ReconNow TEXT, 
    Exp2Sage TEXT, 
    FundID LONG, 
    VatAmount UNKNOWN, 
    NetAmount UNKNOWN, 
    VAT_PERIOD_END_DATE DATETIME, 
    DeleteFlag BIT, 
    SplitIDofSI LONG, 
    DemandRef2 LONG, 
    UnitID2 TEXT, 
    SageAccountNumber2 TEXT, 
    ClientID2 TEXT, 
    PropertyID2 TEXT, 
    FromTranSR TEXT, 
    ToTranSI TEXT,
);


CREATE TABLE rptTransactionSplitTemp (
    ClientID TEXT, 
    DemandID LONG, 
    SplitIDofSI LONG, 
    ReceiptAmount UNKNOWN,
);


CREATE TABLE RptTransactionsSplit (
    TransactionID LONG, 
    FromTran LONG, 
    ToTran LONG, 
    Allocdate DATETIME, 
    ReceiptAmount UNKNOWN, 
    BankCode TEXT, 
    NominalCode TEXT, 
    FundID LONG, 
    NetAmount UNKNOWN, 
    VATAMOUNT UNKNOWN, 
    VAT_PERIOD_END_DATE DATETIME, 
    SplitIDofSI LONG, 
    DeleteFlag BIT, 
    DemandRef3 LONG, 
    UnitID3 TEXT, 
    SageAccountNumber3 TEXT, 
    ClientID3 TEXT, 
    PropertyID3 TEXT, 
    FromTranSR TEXT, 
    ToTranSI TEXT,
);


CREATE TABLE Schedule (
    ScheduleID LONG, 
    ScheduleCode TEXT, 
    ScheduleName TEXT, 
    InsertDate DATETIME, 
    ScheduleStDt DATETIME, 
    ScheduleEndDt DATETIME,
);


CREATE TABLE SecondaryCode (
    PrimaryCode TEXT, 
    Code TEXT, 
    Value TEXT, 
    Description TEXT,
);


CREATE TABLE ShoppingCentre (
    Code INTEGER, 
    Name TEXT, 
    SageDSN TEXT, 
    Contact1 TEXT, 
    Email1 TEXT, 
    DirectLine1 TEXT, 
    Contact2 TEXT, 
    Email2 TEXT, 
    DirectLine2 TEXT, 
    AddressLine1 TEXT, 
    AddressLine2 TEXT, 
    AddressLine3 TEXT, 
    AddressLine4 TEXT, 
    PostCode TEXT, 
    Telephone TEXT, 
    Fax TEXT, 
    Website TEXT, 
    Reference TEXT, 
    DMD_VAT TEXT, 
    Payable_To TEXT, 
    Field8 TEXT, 
    Field7 TEXT, 
    Field6 TEXT, 
    Field3 TEXT, 
    Field2 TEXT, 
    Field1 TEXT, 
    Notes TEXT, 
    SMTP TEXT, 
    UName TEXT, 
    Pws TEXT, 
    Port TEXT, 
    ODM TEXT, 
    SSL BIT, 
    MaxPurChaseHist LONG, 
    MaxPurPaymentHist LONG, 
    MaxSupplierHist LONG, 
    MaxDemandHist LONG, 
    MaxReceiptHist LONG, 
    MaxLesseeHist LONG, 
    MaxCashBookHist LONG, 
    MaxNominalHist LONG, 
    PIShowBal BIT, 
    CurrentVersion TEXT, 
    TLS BIT, 
    isFundassign BIT, 
    isRestrictedtoBudget BIT, 
    isEnvironmentRem BIT, 
    AttachmentLocation TEXT,
);


CREATE TABLE SpareTable1 (
    RecordID TEXT,
);


CREATE TABLE SpareTable10 (
    RecordID TEXT,
);


CREATE TABLE SpareTable4 (
    RecordID TEXT, 
    ClientID TEXT, 
    CategoryCode TEXT, 
    CategoryName TEXT, 
    CatDesc TEXT,
);


CREATE TABLE SpareTable5 (
    RecordID LONG, 
    Code TEXT, 
    ClientID TEXT, 
    CC TEXT,
);


CREATE TABLE SpareTable6 (
    RecordID TEXT,
);


CREATE TABLE SpareTable7 (
    RecordID TEXT,
);


CREATE TABLE SpareTable8 (
    RecordID TEXT,
);


CREATE TABLE SpareTable9 (
    RecordID TEXT,
);


CREATE TABLE SubUnitType (
    ID TEXT, 
    Name TEXT, 
    Description TEXT, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE Supplier (
    SupplierID TEXT, 
    SupplierName TEXT, 
    SupplierAddressLine1 TEXT, 
    SupplierAddressLine2 TEXT, 
    SupplierAddressLine3 TEXT, 
    SupplierAddressLine4 TEXT, 
    SupplierPostCode TEXT, 
    SupplierOfficeEmail TEXT, 
    SupplierPersonalEmail TEXT, 
    SupplierHomeTel TEXT, 
    SupplierMobile TEXT, 
    SupplierOffice TEXT, 
    SupplierOfficeAddressLine1 TEXT, 
    SupplierOfficeAddressLine2 TEXT, 
    SupplierOfficeAddressLine3 TEXT, 
    SupplierOfficeAddressLine4 TEXT, 
    SupplierOfficePostCode TEXT, 
    SupplierOfficeTel TEXT, 
    SupplierOfficePos TEXT, 
    SupplierMemo MEMO, 
    SageSuppAC TEXT, 
    VATReg TEXT, 
    AcBalance UNKNOWN, 
    BacsRef TEXT, 
    SupplierType TEXT, 
    CreditLimit LONG, 
    VATCode TEXT, 
    NominalCode TEXT, 
    AccountType TEXT, 
    PaymentType TEXT, 
    PaymentTerms LONG, 
    SortCode TEXT, 
    AcNo TEXT, 
    AcName TEXT, 
    BPR TEXT, 
    PLControl LONG, 
    PLControlName TEXT, 
    Comments TEXT, 
    TYPE TEXT, 
    OptedtoTax BIT, 
    RentSummaryTemplate TEXT, 
    RemittanceTemplate TEXT, 
    StToLandlordAddress LONG, 
    StToStatementAddress LONG, 
    StLandlordHomeTel TEXT, 
    StLandlordHomeEmail TEXT, 
    StLandlordOfficeTel TEXT, 
    StLandlordStatementEmail TEXT, 
    StLandlordMobile TEXT, 
    StLandlordStatementHometel TEXT, 
    StLandlordOfficeEmail TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE tblBankStatement (
    BSID LONG, 
    ClientBankID LONG, 
    TranDate DATETIME, 
    StatementReference TEXT, 
    MatchedRef TEXT, 
    xMatchedTranID TEXT, 
    Dr UNKNOWN, 
    Cr UNKNOWN,
);


CREATE TABLE tblBatchPayment (
    BP TEXT, 
    BPDate DATETIME, 
    PayOption TEXT, 
    ClientID TEXT, 
    PropertyID TEXT, 
    Bank_ID LONG, 
    SupplierID TEXT, 
    BatchNo TEXT, 
    Generated BIT, 
    ChqNo TEXT, 
    PostingDate TEXT,
);


CREATE TABLE tblBatchReceipt (
    BR TEXT, 
    BRDate DATETIME, 
    RptOption TEXT, 
    ClientID TEXT, 
    PropertyID TEXT, 
    TenantID TEXT, 
    BatchNo TEXT, 
    Generated BIT, 
    ChqNo TEXT, 
    PostingDate DATETIME,
);


CREATE TABLE tblBatchTransaction (
    BT TEXT, 
    TransactionID LONG, 
    BP TEXT, 
    SupplierID TEXT, 
    TranType UNKNOWN, 
    PropertyID TEXT, 
    DueDate DATETIME, 
    Ref TEXT, 
    Details TEXT, 
    Amount UNKNOWN, 
    OSAmt UNKNOWN, 
    PayAmt UNKNOWN, 
    PayDt TEXT, 
    PostingDate DATETIME,
);


CREATE TABLE tblBtRptTran (
    BT TEXT, 
    TransactionID LONG, 
    BR TEXT, 
    TenantID TEXT, 
    TranType UNKNOWN, 
    UnitID TEXT, 
    DueDate DATETIME, 
    Ref TEXT, 
    Details TEXT, 
    Amount UNKNOWN, 
    OSAmt UNKNOWN, 
    RptAmt UNKNOWN, 
    RptDt TEXT, 
    PostingDate DATETIME, 
    fundID TEXT, 
    AmountType TEXT,
);


CREATE TABLE tblPoA (
    TransactionID LONG, 
    SplitID LONG, 
    Type UNKNOWN, 
    SageAccountNumber TEXT, 
    UnitID TEXT, 
    TDate DATETIME, 
    DDate DATETIME, 
    Ref TEXT, 
    Details TEXT, 
    Amount UNKNOWN, 
    OSAllocation UNKNOWN, 
    AllocatedAmt UNKNOWN, 
    Allocation LONG, 
    IsSageUpdate BIT, 
    UpDateSage BIT, 
    PoAView BIT, 
    BankCode TEXT, 
    NominalCode TEXT, 
    ExtRef TEXT, 
    TransType UNKNOWN, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT,
);


CREATE TABLE tblPrevGLU (
    ID INTEGER, 
    LeaseID TEXT, 
    ChildID TEXT, 
    SAN TEXT, 
    UnitNumber TEXT, 
    Freq UNKNOWN, 
    DmdType LONG, 
    ChargingMethod TEXT, 
    MethodType TEXT, 
    Value DOUBLE, 
    ExValue DOUBLE, 
    NewValue DOUBLE, 
    ExYrTotal DOUBLE, 
    NewYrTotal DOUBLE, 
    ExDueEachPeriod DOUBLE, 
    NewDueEachPeriod DOUBLE, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT,
);


CREATE TABLE tblPurInv (
    MY_ID TEXT, 
    SlNumber LONG, 
    SUPP_AC TEXT, 
    TRAN_DATE DATETIME, 
    TransactionType UNKNOWN, 
    INV_NO TEXT, 
    TOTAL_AMOUNT UNKNOWN, 
    UPDATE_SAGE BIT, 
    DR_CR BIT, 
    RECHARGED BIT, 
    TTP UNKNOWN, 
    CATEGORY_CODE UNKNOWN, 
    History BIT, 
    CL_ID TEXT, 
    TrfPayment BIT, 
    ScheduleID LONG, 
    Prn TEXT, 
    PropertyID TEXT, 
    NLPost BIT, 
    DueDate TEXT, 
    PostingDate DATETIME, 
    PO TEXT, 
    isManagementFee BIT, 
    ManagementFeeSL LONG, 
    ReportInvNetAmount UNKNOWN, 
    ReportINVVATAmount UNKNOWN, 
    ReportPaymentAmount UNKNOWN, 
    ReportPayDescription TEXT, 
    ReportNominalCode TEXT, 
    ReportNominalName TEXT, 
    ReportFromDate DATETIME, 
    ReportToDate DATETIME, 
    isRentPayable BIT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME, 
    isOSAmountShown BIT, 
    isOSAmountShownPrev BIT, 
    StatementIDPrev LONG, 
    StatementID LONG,
);


CREATE TABLE tblPurInvPreview (
    MY_ID TEXT, 
    SlNumber LONG, 
    Supp_AC TEXT, 
    TRAN_DATE DATETIME, 
    TransactionType LONG, 
    Inv_no TEXT, 
    TOTAL_AMOUNT UNKNOWN, 
    UPDATE_SAGE BIT, 
    DR_CR BIT, 
    RECHARGED BIT, 
    TTP LONG, 
    CATEGORY_CODE LONG, 
    History BIT, 
    CL_ID TEXT, 
    TrfPayment BIT, 
    ScheduleID LONG, 
    Prn TEXT, 
    PropertyID TEXT, 
    DueDate DATETIME, 
    NLPost BIT, 
    PostingDate DATETIME, 
    PO TEXT, 
    ReportFromDatePreview DATETIME, 
    ReportToDatePreview DATETIME, 
    DescriptionANDDates TEXT,
);


CREATE TABLE tblPurInvSRec (
    MY_ID TEXT, 
    ParentID TEXT, 
    TRAN_ID TEXT, 
    TRANS TEXT, 
    UNIT_ID TEXT, 
    NOMINAL_CODE TEXT, 
    DEPT_ID LONG, 
    PROJ_REF TEXT, 
    COST_CODE TEXT, 
    JOB_ID TEXT, 
    DESCRIPTION TEXT, 
    NET_AMOUNT UNKNOWN, 
    TAX_CODE TEXT, 
    VAT UNKNOWN, 
    TOTAL_AMOUNT UNKNOWN, 
    UPDATE_SAGE BIT, 
    RECHARGED BIT, 
    CATEGORY_CODE UNKNOWN, 
    ScheduleID LONG, 
    CL_ID TEXT, 
    RecoverablePt SINGLE, 
    Invoiced BIT, 
    PoPiCross TEXT, 
    TrfPayment BIT,
);


CREATE TABLE tblPurInvSRecPreview (
    MY_ID TEXT, 
    ParentID TEXT, 
    TRAN_ID TEXT, 
    TRANS TEXT, 
    UNIT_ID TEXT, 
    NOMINAL_CODE TEXT, 
    DEPT_ID LONG, 
    PROJ_REF TEXT, 
    COST_CODE TEXT, 
    JOB_ID TEXT, 
    DESCRIPTION TEXT, 
    NET_AMOUNT UNKNOWN, 
    TAX_CODE TEXT, 
    VAT UNKNOWN, 
    TOTAL_AMOUNT UNKNOWN, 
    UPDATE_SAGE BIT, 
    RECHARGED LONG, 
    CATEGORY_CODE LONG, 
    ScheduleID LONG, 
    CL_ID TEXT, 
    RecoverablePt LONG, 
    TrfPayment BIT, 
    Invoiced BIT, 
    PoPiCross TEXT,
);


CREATE TABLE Template (
    TemplateID LONG, 
    TemplateName TEXT, 
    SenderName TEXT, 
    SenderPosition TEXT, 
    Salutation TEXT, 
    Body MEMO, 
    TemplateDate DATETIME, 
    ModifiedDate DATETIME, 
    ModifiedBy TEXT, 
    Description TEXT, 
    TempType TEXT, 
    OurRef TEXT,
);


CREATE TABLE TemplateUnitSelection (
    ID LONG, 
    TemplateID LONG, 
    UnitNumber TEXT,
);


CREATE TABLE TenantBankDetails (
    BankTenantID TEXT, 
    BankID TEXT, 
    BankACNumber TEXT, 
    BankACName TEXT, 
    BankSortCode TEXT, 
    IsDefaultAC BIT, 
    PaymentMethod TEXT, 
    BacsRef TEXT, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE TenantDeposit (
    DepositID TEXT, 
    TenantID TEXT, 
    BankCode TEXT, 
    NominalCode TEXT, 
    DepositDate DATETIME, 
    DptAmtType TEXT, 
    DptDetails TEXT, 
    DptAmount UNKNOWN, 
    DptVatRate UNKNOWN, 
    DptRefund BIT, 
    RefundRef TEXT, 
    Status BIT, 
    Deleted BIT, 
    BCName TEXT, 
    NCName TEXT, 
    BankTransaction BIT, 
    OSRefund UNKNOWN, 
    DptType TEXT, 
    GroupNo DOUBLE, 
    TransactionID TEXT, 
    FundID LONG, 
    ParentRFID TEXT, 
    DepositTypePrefix TEXT, 
    DepositSL LONG,
);


CREATE TABLE TenantEventHistory (
    EventHistoryID TEXT, 
    EventTenantID TEXT, 
    EventType TEXT, 
    ReportedDate DATETIME, 
    Description TEXT, 
    DateCompleted DATETIME, 
    TaskOwner TEXT, 
    Contact TEXT, 
    RemindDate DATETIME, 
    Alarm BIT, 
    REMINDER_ID TEXT,
);


CREATE TABLE Tenants (
    SageAccountNumber TEXT, 
    TenantID TEXT, 
    Name TEXT, 
    CompanyName TEXT, 
    Contact1 TEXT, 
    Email1 TEXT, 
    DirectLine1 TEXT, 
    Contact2 TEXT, 
    Email2 TEXT, 
    DirectLine2 TEXT, 
    HOAddressLine1 TEXT, 
    HOAddressLine2 TEXT, 
    HOAddressLine3 TEXT, 
    HOAddressLine4 TEXT, 
    HOPostCode TEXT, 
    HOTelephone TEXT, 
    HOFax TEXT, 
    BillAddressLine1 TEXT, 
    BillAddressLine2 TEXT, 
    BillAddressLine3 TEXT, 
    BillAddressLine4 TEXT, 
    BillPostCode TEXT, 
    BillTelephone TEXT, 
    BillFax TEXT, 
    InvoiceTo TEXT, 
    CurrentRental_ TEXT, 
    Comments TEXT, 
    TenantMemo MEMO, 
    OCCUPIDE_ BIT, 
    Balance UNKNOWN, 
    Deposite UNKNOWN, 
    BankCode TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    spare9 TEXT, 
    TemplatePrint TEXT, 
    FirstPay UNKNOWN, 
    FurtherPay UNKNOWN, 
    Freq TEXT, 
    Ref TEXT, 
    StDate DATETIME, 
    RCCComments TEXT, 
    EmailDmd BIT, 
    EmailSt BIT, 
    CombEmail BIT, 
    EmailSC BIT, 
    SLControl TEXT, 
    DefaultNC TEXT, 
    VAT_CODE TEXT, 
    RCCComments2 TEXT, 
    isCurrent BIT, 
    CurrUnit TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME, 
    UnitName TEXT, 
    PropertyID TEXT, 
    PropertyName TEXT, 
    ClientID TEXT, 
    ClientName TEXT,
);


CREATE TABLE tlbAgreement (
    AGREEMENT_ID LONG, 
    CPA_ID LONG, 
    AGR_DATE DATETIME, 
    CHARGE_TYPE UNKNOWN, 
    DEMAND_TYPE LONG, 
    INCOME_TYPE TEXT, 
    CHARGE_METHOD TEXT, 
    CHARGE_BASIS TEXT, 
    AnnualCharge UNKNOWN, 
    START_DATE DATETIME, 
    END_DATE TEXT, 
    REVIEW_DATE_ DATETIME, 
    NOTICE_DAYS_ INTEGER, 
    Fund LONG, 
    Handling TEXT, 
    Frequency LONG, 
    NtDueDate DATETIME, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    ManagingAgentID TEXT, 
    TotalAmount DOUBLE, 
    EachPeriod DOUBLE, 
    StopDate TEXT, 
    CapAmount DOUBLE, 
    FDD DATETIME, 
    amount UNKNOWN, 
    LastChargeDate DATETIME, 
    ReportClientID TEXT, 
    ReportPropertyID TEXT,
);


CREATE TABLE tlbBank (
    BANK_ID TEXT, 
    SORT_CODE TEXT, 
    BANK_BRANCH TEXT, 
    BANK_NAME TEXT, 
    BANK_ADDRESS1 TEXT, 
    BANK_ADDRESS2 TEXT, 
    BANK_ADDRESS3 TEXT, 
    BANK_ADDRESS4 TEXT, 
    BANK_POST_CODE TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    Contact TEXT, 
    Tel TEXT, 
    Fax TEXT, 
    Mobile TEXT, 
    eMail TEXT, 
    Website TEXT,
);


CREATE TABLE tlbBankPayment (
    MY_ID TEXT, 
    TRAN_ID TEXT, 
    BANK_AC TEXT, 
    TRAN_DATE DATETIME, 
    TRANS TEXT, 
    TRAN_TYPE TEXT, 
    UNIT_ID TEXT, 
    NOMINAL_CODE TEXT, 
    DEPT_ID LONG, 
    PROJ_REF TEXT, 
    COST_CODE TEXT, 
    DESCRIPTION TEXT, 
    NET_AMOUNT UNKNOWN, 
    TAX_CODE TEXT, 
    VAT UNKNOWN, 
    UPDATE_SAGE BIT, 
    RECHARGED BIT, 
    RECHARABLE BIT, 
    TransactionType UNKNOWN, 
    SAGEPostingNumber LONG, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    PropertyID TEXT, 
    ClientID TEXT, 
    Reconciled UNKNOWN, 
    ReconNow TEXT, 
    CT TEXT, 
    TenantDeposit TEXT, 
    PostingDate DATETIME, 
    NLPost BIT, 
    DateTimeStamp TEXT, 
    Module TEXT, 
    UserSessionID TEXT, 
    WindowsUserName TEXT, 
    MachineName TEXT, 
    PrestigeUserName TEXT, 
    ServerIPaddress TEXT, 
    RentSumStatement TEXT, 
    RentSumStatementPreview TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE tlbBankReconcilation (
    MY_ID TEXT, 
    TransactionType UNKNOWN, 
    RefID TEXT, 
    AccountNum TEXT, 
    UnitID TEXT, 
    TDate DATETIME, 
    DDate DATETIME, 
    TRef TEXT, 
    Details TEXT, 
    Amount UNKNOWN, 
    OSAmount UNKNOWN, 
    ReconAmount UNKNOWN, 
    ReconDate DATETIME, 
    ReconType TEXT, 
    BankCode TEXT, 
    NominalCode TEXT, 
    ExtRef TEXT, 
    TranMth TEXT, 
    SlNumber LONG, 
    FundID LONG, 
    Recoverable SINGLE, 
    ClientID TEXT,
);


CREATE TABLE tlbBankReconClosingBal (
    MY_ID TEXT, 
    ClientID TEXT, 
    BankCode TEXT, 
    StatementDate DATETIME, 
    AccBal UNKNOWN, 
    StOpenBal UNKNOWN, 
    ProjClBal UNKNOWN,
);


CREATE TABLE tlbBatchReceiptUploadFile (
    FileName TEXT, 
    UploadDate DATETIME, 
    UploadedBy TEXT, 
    UploadedFrom TEXT,
);


CREATE TABLE tlbChildDemandRecord (
    ChildDemandRecID TEXT, 
    Batch INTEGER, 
    AutomaticManual TEXT, 
    SageAccountNumber TEXT, 
    TenantCompanyName TEXT, 
    UnitNumber TEXT, 
    NominalCodeforAmount TEXT, 
    NominalNameforAmount TEXT, 
    NominalCodeforVAT TEXT, 
    NominalNameforVAT TEXT, 
    NominalCodeforTotal TEXT, 
    NominalNameforTotal TEXT, 
    Source INTEGER, 
    TransactionType INTEGER, 
    TotalAmount DOUBLE, 
    VATAmount DOUBLE, 
    Amount DOUBLE, 
    IssueDate TEXT, 
    VATMonth INTEGER, 
    DueDate TEXT, 
    TypeOfDemand INTEGER, 
    Reference TEXT, 
    Text TEXT, 
    Description TEXT, 
    IsPrinted TEXT, 
    SendToPrint TEXT, 
    ExportedToSage TEXT, 
    ExportedToExcel TEXT, 
    ParentDemandRecID TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    spare9 TEXT, 
    spare10 TEXT,
);


CREATE TABLE tlbClientBanks (
    MY_ID LONG, 
    CLIENT_ID TEXT, 
    BANK_ID TEXT, 
    Bank_AC_Name TEXT, 
    BANK_AC_NUM TEXT, 
    BANK_SC TEXT, 
    DEFAULT_AC BIT, 
    PaymentMethod TEXT, 
    BacsRef TEXT, 
    NominalCode TEXT, 
    CurrentBalance UNKNOWN, 
    MinimumLimit UNKNOWN, 
    AccountType TEXT, 
    ExpireDate DATETIME, 
    Contact TEXT, 
    Telephone TEXT, 
    Fax TEXT, 
    email TEXT, 
    website TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    LRSD TEXT, 
    ClosingBal UNKNOWN, 
    Indentifier TEXT, 
    FileExten TEXT, 
    FileLoc TEXT, 
    EB TEXT, 
    NxtChqNum TEXT, 
    BankMemo MEMO, 
    PCB UNKNOWN, 
    LSD TEXT, 
    SOB UNKNOWN, 
    PCB_ABR UNKNOWN, 
    FileLoc_ TEXT, 
    SelBanks TEXT, 
    AllowOverDraft BIT, 
    OverDraftLimit UNKNOWN, 
    consolidated BIT, 
    ProcessFileLoc TEXT, 
    ConsolidatedBankID LONG, 
    ConsBankACNumber TEXT, 
    ConsSortCode TEXT, 
    conBankCode TEXT, 
    conBankReadOnly LONG, 
    LASTBACSFDATE DATETIME, 
    LASTBACSFNO LONG,
);


CREATE TABLE tlbCreditNote (
    MY_ID TEXT, 
    TRAN_ID TEXT, 
    SUPP_AC TEXT, 
    TRAN_DATE DATETIME, 
    TRANS TEXT, 
    TRAN_TYPE TEXT, 
    UNIT_ID TEXT, 
    INV_NO TEXT, 
    NOMINAL_CODE TEXT, 
    DEPT_ID TEXT, 
    PROJ_REF TEXT, 
    COST_CODE TEXT, 
    DESCRIPTION TEXT, 
    NET_AMOUNT UNKNOWN, 
    TAX_CODE TEXT, 
    VAT UNKNOWN, 
    UPDATE_SAGE BIT, 
    PAYMENT UNKNOWN, 
    OUT_PAYMENT UNKNOWN, 
    DR_CR BIT, 
    RECHARGED BIT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT,
);


CREATE TABLE tlbDRCurrentPrint (
    UniqueRefNumber LONG, 
    Batch TEXT, 
    AutomaticManual TEXT, 
    SageAccountNumber TEXT, 
    UnitNumber TEXT, 
    NominalCodeforAmount TEXT, 
    NominalNameforAmount TEXT, 
    NominalCodeforVAT TEXT, 
    NominalNameforVAT TEXT, 
    NominalCodeforTotal TEXT, 
    NominalNameforTotal TEXT, 
    Source INTEGER, 
    TransactionType INTEGER, 
    TotalAmount DOUBLE, 
    VATAmount DOUBLE, 
    Amount DOUBLE, 
    IssueDate TEXT, 
    VATMonth INTEGER, 
    DUEDATE DATETIME, 
    TypeOfDemand LONG, 
    Reference TEXT, 
    Text TEXT, 
    Description TEXT, 
    IsPrinted TEXT, 
    SendToPrint TEXT, 
    ExportedToSage TEXT, 
    ExportedToExcel TEXT, 
    Print_ID TEXT, 
    DemandFrom DATETIME, 
    DemandTo DATETIME, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT, 
    spare7 TEXT, 
    spare8 TEXT, 
    spare9 TEXT, 
    spare10 TEXT, 
    CombEmail BIT, 
    DemandReportName TEXT, 
    DTCategory UNKNOWN, 
    ChargingFigure UNKNOWN, 
    SptSlNo INTEGER, 
    PrintBBF BIT, 
    EmailSC BIT, 
    MINDUEDATE DATETIME,
);


CREATE TABLE tlbFloor (
    MY_ID TEXT, 
    UNIT_ID TEXT, 
    FLOOR SINGLE, 
    FLOOR_AREA SINGLE, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE tlbID (
    ID LONG, 
    NameTable TEXT, 
    LastId TEXT, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE tlbImages (
    PREMISIS_ID TEXT, 
    PREMISIS_TYPE TEXT, 
    PREMISIS_IMAGE UNKNOWN, 
    IMAGE_NAME TEXT, 
    IMAGE_PATH TEXT, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE tlbLetterReports (
    Id LONG, 
    SageAccountNumber TEXT, 
    UnitNo TEXT, 
    LesseeName TEXT, 
    AddressLine1 TEXT, 
    AddressLine2 TEXT, 
    AddressLine3 TEXT, 
    AddressLine4 TEXT, 
    PostCode TEXT, 
    printDate DATETIME, 
    Subject TEXT, 
    Body MEMO, 
    SenderName TEXT, 
    SenderPosition TEXT, 
    isPrint TEXT, 
    TemplateID LONG, 
    TEmail TEXT,
);


CREATE TABLE tlbMemo (
    MEMO_ID TEXT, 
    MEMO_DATE DATETIME, 
    MEMO_BODY MEMO, 
    spare1 TEXT, 
    spare2 TEXT,
);


CREATE TABLE tlbPayable (
    PAYABLE_ID LONG, 
    CPA_ID LONG, 
    PAY_DATE DATETIME, 
    PAYABLE_TYPE UNKNOWN, 
    PAY_DEMAND_TYPE UNKNOWN, 
    PAYABLE_METHOD TEXT, 
    PAYABLE_BASIS_ TEXT, 
    PAY_AnnualCharge UNKNOWN, 
    PAY_START_DATE DATETIME, 
    PAY_END_DATE DATETIME, 
    PAY_FUND LONG, 
    PAY_HANDLING TEXT, 
    PAY_FREQUENCY TEXT, 
    PAY_NtDueDate DATETIME, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    clientLandlordID TEXT, 
    AmountOrPercentage TEXT, 
    Percentage DOUBLE, 
    StopDate DATETIME, 
    ONDD BIT, 
    ClientID TEXT, 
    Printed BIT, 
    Emailed BIT, 
    Invoiced BIT, 
    PayeeType TEXT,
);


CREATE TABLE tlbPayment (
    TransactionID LONG, 
    Type UNKNOWN, 
    PI TEXT, 
    SageAccountNumber TEXT, 
    UnitID TEXT, 
    PDate DATETIME, 
    DDate DATETIME, 
    Ref TEXT, 
    Details TEXT, 
    Amount UNKNOWN, 
    OSAmount UNKNOWN, 
    PaymentAmount UNKNOWN, 
    Discount UNKNOWN, 
    Allocation LONG, 
    IsSageUpdate BIT, 
    UpDateSage BIT, 
    PaymentView BIT, 
    MFCharged BIT, 
    BankCode TEXT, 
    NominalCode TEXT, 
    ExtRef TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    SageDepartment UNKNOWN, 
    IntCalDate TEXT, 
    PayAmtType TEXT, 
    AdjTag TEXT, 
    PoA_SPN LONG, 
    spare1 TEXT, 
    SlNumber LONG, 
    ChqNo TEXT, 
    Reconciled UNKNOWN, 
    ReconNow TEXT, 
    FundID LONG, 
    PostToNL TEXT, 
    Recoverable SINGLE, 
    szTransactionID TEXT, 
    ClientID TEXT, 
    NLPost BIT, 
    PostingDate DATETIME, 
    isPrint BIT, 
    DateTimeStamp TEXT, 
    Module TEXT, 
    UserSessionID TEXT, 
    WindowsUserName TEXT, 
    MachineName TEXT, 
    PrestigeUserName TEXT, 
    ServerIPaddress TEXT, 
    RentSumStatement TEXT, 
    RentSumStatementPreview TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE tlbPaymentSplit (
    TransactionID TEXT, 
    PayHeader LONG, 
    FundID LONG, 
    Amount UNKNOWN, 
    OSAmount UNKNOWN, 
    SplitID INTEGER, 
    DueDate DATETIME, 
    Description TEXT, 
    AllocTranID TEXT, 
    JobID TEXT, 
    NOMINAL_CODE TEXT, 
    TRANS TEXT, 
    UNIT_ID TEXT, 
    ScheduleID LONG, 
    RecoverablePt SINGLE, 
    PIRef TEXT, 
    PayTransactionIDSplit LONG, 
    PropertyID TEXT, 
    ClientStatementID LONG, 
    ClientStatementPrevID LONG,
);


CREATE TABLE tlbReceipt (
    TransactionID LONG, 
    Type UNKNOWN, 
    DemandRef LONG, 
    SageAccountNumber TEXT, 
    UnitID TEXT, 
    RDate DATETIME, 
    DDate DATETIME, 
    Ref TEXT, 
    Details TEXT, 
    Amount UNKNOWN, 
    OSAmount UNKNOWN, 
    ReceiptAmount UNKNOWN, 
    Discount UNKNOWN, 
    Allocation LONG, 
    IsSageUpdate BIT, 
    UpDateSage BIT, 
    ReceiptView BIT, 
    MFCharged BIT, 
    BankCode TEXT, 
    NominalCode TEXT, 
    ExtRef TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    SlNumber LONG, 
    IntCalDate TEXT, 
    RptAmtType TEXT, 
    AdjTag TEXT, 
    PoA_SPN LONG, 
    spare1 TEXT, 
    Reconciled UNKNOWN, 
    ReconNow TEXT, 
    FundID LONG, 
    szTransactionID TEXT, 
    NLPost BIT, 
    PostingDate DATETIME, 
    ClientID TEXT, 
    DateTimeStamp TEXT, 
    Module TEXT, 
    UserSessionID TEXT, 
    WindowsUserName TEXT, 
    MachineName TEXT, 
    PrestigeUserName TEXT, 
    ServerIPaddress TEXT, 
    RentSumStatement TEXT, 
    ChargeDate DATETIME, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME, 
    PropertyID4 TEXT,
);


CREATE TABLE tlbReceiptSplit (
    TransactionID TEXT, 
    RptHeader LONG, 
    FundID LONG, 
    Amount UNKNOWN, 
    OSAmount UNKNOWN, 
    SplitID INTEGER, 
    DueDate DATETIME, 
    Description TEXT, 
    AllocTranID TEXT, 
    JobID TEXT, 
    RptTransactionsIDSplit LONG, 
    PropertyID TEXT, 
    ISMGTFeeS BIT, 
    ClientStatementID LONG, 
    ClientStatementPrevID LONG, 
    PIREFMGTFEES TEXT, 
    ChargeDateS DATETIME,
);


CREATE TABLE tlbRecharged (
    MY_ID TEXT, 
    RECHARGE_DATE DATETIME, 
    CLIENT_ID TEXT, 
    TYPE TEXT, 
    EX_REF TEXT, 
    TRANS TEXT, 
    UNIT_ID TEXT, 
    NOMINAL_CODE TEXT, 
    DEPT_ID TEXT, 
    PROJ_REF TEXT, 
    DESCRIPTION TEXT, 
    RECHARGE UNKNOWN, 
    VAT UNKNOWN, 
    UPDATE_SAGE BIT, 
    TYPE_ORG TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT,
);


CREATE TABLE tlbRechargePre (
    MY_ID TEXT, 
    UNIT_ID TEXT, 
    LANDLORD_ID TEXT, 
    TRAN_ID TEXT, 
    TRAN_DATE DATETIME, 
    TRAN_TYPE TEXT, 
    TRANS TEXT, 
    INV_NO TEXT, 
    NOMINAL_CODE TEXT, 
    DEPT_ID TEXT, 
    PROJ_REF TEXT, 
    COST_CODE TEXT, 
    DESCRIPTION TEXT, 
    NET_AMOUNT UNKNOWN, 
    VAT UNKNOWN, 
    RECHARGE UNKNOWN, 
    CHECKED BIT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    spare6 TEXT,
);


CREATE TABLE tlbRef (
    MY_ID TEXT, 
    LAST_REF LONG,
);


CREATE TABLE tlbTransactionTypes (
    TYPE_ID UNKNOWN, 
    DESCRIPTION TEXT, 
    CONSTANT TEXT, 
    ACCOUNTS_LINE TEXT, 
    Group TEXT, 
    spare2 TEXT, 
    CtrlCode TEXT,
);


CREATE TABLE tlbVatCode (
    VAT_ID INTEGER, 
    VAT_CODE TEXT, 
    VAT_RATE SINGLE, 
    IN_USE BIT, 
    DESCRIPTIONS TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    OnReturn BIT,
);


CREATE TABLE TransactionQueue (
    ID TEXT, 
    moduleName TEXT, 
    user TEXT, 
    timecreated DATETIME, 
    Time1 LONG, 
    IP TEXT,
);


CREATE TABLE UnitAnalysis (
    UnitAnalysisID LONG, 
    UnitNumber TEXT, 
    AnalysisType TEXT, 
    AnalysisDescription TEXT, 
    AnalysisOption TEXT, 
    AnalysisValue DOUBLE, 
    AnalysisQuantity DOUBLE, 
    AnalysisPercentage DOUBLE, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT,
);


CREATE TABLE UnitInsurance (
    UnitInsuranceID TEXT, 
    UnitNumber TEXT, 
    Insurer TEXT, 
    InsuranceType TEXT, 
    PolicyNo TEXT, 
    SumInsured DOUBLE, 
    AnnualPR DOUBLE, 
    MonthlyPR DOUBLE, 
    ExpiryDate DATETIME, 
    RechargeableAmount DOUBLE, 
    RechargeableFreq TEXT, 
    InsContact TEXT, 
    Telephone TEXT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    spare4 TEXT, 
    spare5 TEXT, 
    Usage TEXT, 
    LeaseID TEXT, 
    StartDate TEXT, 
    Comments TEXT, 
    Attachment TEXT, 
    Module TEXT,
);


CREATE TABLE UnitMaintHistory (
    ID LONG, 
    UnitNumber TEXT, 
    MaintenanceType TEXT, 
    ReportedDate DATETIME, 
    Description TEXT, 
    DateCompleted DATETIME, 
    TaskOwner TEXT, 
    Contact TEXT, 
    RemindDate DATETIME, 
    Alarm BIT, 
    EstimateCost DOUBLE, 
    REMINDER_ID TEXT,
);


CREATE TABLE Units (
    UnitNumber TEXT, 
    PropertyID TEXT, 
    UnitName TEXT, 
    UnitAddressLine1 TEXT, 
    UnitAddressLine2 TEXT, 
    UnitAddressLine3 TEXT, 
    UnitAddressLine4 TEXT, 
    UnitPostCode TEXT, 
    Occupied TEXT, 
    TenantCompanyName TEXT, 
    SageAccountNumber TEXT, 
    Frontage LONG, 
    RateableValue LONG, 
    RatesPayable LONG, 
    GroundFloorArea LONG, 
    MezzanineArea LONG, 
    TotalArea LONG, 
    UnitType TEXT, 
    Status_ TEXT, 
    LandLord TEXT, 
    Management TEXT, 
    Memo MEMO, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    RentalPrice TEXT, 
    UnitUsages TEXT, 
    isPrint TEXT, 
    LastModifiedBy TEXT, 
    LastModifiedDate DATETIME, 
    CreatedBy TEXT, 
    CreatedDate DATETIME,
);


CREATE TABLE UnitSafety (
    UnitSafetyID TEXT, 
    UnitNumber TEXT, 
    SafetyType TEXT, 
    SafetyInspection TEXT, 
    NextDueDate DATETIME, 
    SafetyStatus TEXT, 
    InspectedBy TEXT, 
    SafetyTelephone TEXT, 
    Certificate BIT, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    LastDate TEXT, 
    Comment TEXT, 
    Alarm TEXT, 
    Attachment TEXT, 
    Module TEXT,
);


CREATE TABLE UnitUtilities (
    UnitUtilitiesID LONG, 
    UnitNumber TEXT, 
    Authority_Supplier TEXT, 
    UtilitiesType TEXT, 
    UtilitiesReference TEXT, 
    ChargeRate DOUBLE, 
    UtilitiesTelephone TEXT, 
    FinalReading TEXT, 
    DateVacated DATETIME, 
    spare1 TEXT, 
    spare2 TEXT, 
    spare3 TEXT, 
    Occupier TEXT, 
    Status TEXT, 
    StartDate TEXT, 
    InitialReading TEXT, 
    Comments TEXT, 
    Module TEXT,
);


CREATE TABLE UserNames (
    UserName TEXT, 
    Password TEXT, 
    spare1 TEXT, 
    spare2 TEXT,
);


